### ISSUE TITLE
variantqc: parse error: "-o" is not a valid option

### ISSUE THREAD

**Issue by osoylemez** [hail-is/hail#1017]
Hi - I receive the following error when running the `variantqc` example from the [Getting Started documentation](https://hail.is/getting_started.html):

`$ ./build/install/hail/bin/hail read ~/sample.vds splitmulti variantqc -o ~/variantqc.tsv sampleqc -o ~/sampleqc.tsv
`

`hail: fatal: variantqc: parse error: "-o" is not a valid option`

Leaving `variantqc` out runs without error and generates the sampleqc output.

**Comment by tpoterba** [comment]
Good catch!  We removed this option a week or two ago because it prevented us from making performance improvements.  

There's an example here which shows how to export the variantqc annotations with the expression-based `exportvariants` command:

http://discuss.hail.is/t/export-feature-added-splatting-structs-into-multiple-columns/59

**Comment by tpoterba** [comment]
I'll fix this up now.

**Comment by tpoterba** [comment]
to clarify, here's the new command to run:
```
$ ./build/install/hail/bin/hail read ~/sample.vds \
  splitmulti \
  sampleqc -o ~/sampleqc.tsv \
  variantqc \
  exportvariants -o ~/variantqc.tsv -c 'Variant = v, va.qc.*' \
  printschema
```
