### ISSUE TITLE
Compiled libs in repo

### ISSUE THREAD

**Issue by vladsaveliev** [hail-is/hail#10170]
Hi there!

I'm just wondering if you meant to add the `.dylib` and `.so` files in the repository? https://github.com/hail-is/hail/tree/main/hail/prebuilt/lib/darwin
They get overwritten on re-builds from source.

**Comment by tpoterba** [comment]
Sorry, didn't see this earlier -- 

this is intentional. We do this so that we don't require users to recompile the C libraries when the install the Python library. Our native library distribution story is definitely a work in progress and this will change (hopefully improve) in the future.

Feel free to ping us if this answer isn't sufficient!
