### ISSUE TITLE
Is LCR filtering done by 'contains' or 'overlap'?

### ISSUE THREAD

**Issue by ConnorBarnhill** [hail-is/hail#10205]
Essentially, if I do this:
```
mt = mt.filter_rows(
  (hl.is_missing(lcr[mt.locus]))
)
```
Is it removing any locus that is contained in any of the lcr intervals, or removing any locus that overlaps with any of the lcr intervals?

**Comment by ConnorBarnhill** [comment]
Looks like it's overlap, in other words:
```
(
  variants_df
    .join(
      lcr_df, 
      on=[
        variants_df.contigName == lcr_df.contigName,
        variants_df.start < lcr_df.end,
        lcr_df.start <= variants_df.end
      ],
      how='left_anti'
    )
)
```

**Comment by tpoterba** [comment]
Missed this until now, sorry! I'm not quite sure about the difference between contains/overlap here. Do you mean the inclusivity of the endpoints? That's actually a parameter of Hail intervals, see [here](https://hail.is/docs/0.2/hail.expr.IntervalExpression.html#hail.expr.IntervalExpression.includes_end) for the methods.

The `lcr` intervals were probably constructed by [parse_locus_interval](https://hail.is/docs/0.2/functions/genetics.html#hail.expr.functions.parse_locus_interval), which produces left-inclusive, right-exclusive intervals unless otherwise specified.
