### ISSUE TITLE
hail-python.zip location

### ISSUE THREAD

**Issue by yc000000** [hail-is/hail#10844]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

Where's "hail-python.zip" in Hail 0.2 (latest version)

we used to be able to use ```aws s3 cp distributions/hail-python.zip s3://${RESOURCES_BUCKET}/artifacts/``` on aws to install Hail but this failed when we switched from 0.1 to 0.2.

Has anyone encountered similar issues before?

**Comment by danking** [comment]
Hail is no longer distributed as a zip file. You should use `make install-on-cluter` (described further [here](https://hail.is/docs/0.2/install/other-cluster.html)) to install Hail on a cluster.

I do not recommend creating a wheel or zip file because the native binaries included in that wheel or zip file might be incompatible with the computer on which you install that file. If you are absolutely certain that the build machine *and the executing machine* can share native binaries, then you can do this:
```
make wheel HAIL_COMPILE_NATIVES=1
```
This produces a wheel file at `build/deploy/dist/hail-0.2.XX-py3-none-any.whl` where XX is the current patch version of Hail.

**Comment by yc000000** [comment]
Thank you for getting back to me. I was using the solution provided by aws (https://github.com/awslabs/genomics-tertiary-analysis-and-data-lakes-using-aws-glue-and-amazon-athena/blob/master/source/GenomicsAnalysisCode/buildhail_buildspec.yml) also the main page for reference (https://docs.aws.amazon.com/solutions/latest/genomics-tertiary-analysis-and-data-lakes-using-aws-glue-and-amazon-athena/welcome.html)

In order to use the latest Hail (because we have vcf format 4.3 which is not supported in Hail 0.1), we changed it to 
```

          echo 'Installing pre-reqs'
          yum install -y g++ cmake git
          yum install -y lz4
          yum install -y lz4-devel
          git clone $HAIL_REPO
          cd hail/hail && git fetch && git checkout main
          ./gradlew clean
          make install HAIL_COMPILE_NATIVES=1
          make install HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.13 SPARK_VERSION=3.1.1
          cd build
          pip download decorator==4.2.1
          aws s3 cp decorator-4.2.1-py2.py3-none-any.whl s3://${RESOURCES_BUCKET}/artifacts/decorator.zip
          aws s3 cp distributions/hail-python.zip s3://${RESOURCES_BUCKET}/artifacts/
          aws s3 cp libs/hail-all-spark.jar s3://${RESOURCES_BUCKET}/artifacts/
``` 

What else I should change in order to deploy this solution successfully? 

Thank you for the help!

**Comment by danking** [comment]
Hi @yc000000, unfortunately, I don't know how Amazon Glue works. I don't know the purpose of copying the Hail jar into S3. You might try uploading the wheel file instead of the zip file. 

You might also try instead using the HMS DBMI scripts for starting a [Hail Cluster on AWS Spot instances](https://github.com/hms-dbmi/hail-on-AWS-spot-instances).

At the end of the day, installing hail is really quite simple. Once you have a Spark cluster, you just need to:

1. ssh to the master node of the Spark Cluster.
2. clone the hail repository.
3. run `make -C hail/hail install HAIL_COMPILE_NATIVES=1`

After that you should be able to submit Python files using Hail to the cluster.
