### ISSUE TITLE
website search returns error 404

### ISSUE THREAD

**Issue by tdelcourt** [hail-is/hail#13377]
### What happened?

Searching for experimental.vcf_combiner or experimental.densify or experimental.lgt_to_gt returns links that lead to error 404. They used to work fine.
The pages don't seem to exist at all (eg https://hail.is/docs/0.2/_modules/hail/experimental/vcf_combiner/densify.html), as via a google search it also fails.
Were the pages removed for a reason? I don't see anything in the changelogs.

### Version

0.2.117

**Comment by danking** [comment]
Hey @tdelcourt !

Please accept my apology for the disruption to your work. Unlike every other part of Hail, we do not guarantee backwards compatibility between versions of the `hail.experimental`  module. It's a collection of, well, experimental tools that we're working on but which are not yet ready for broad use.

A couple years ago, the functionality which you seek was moved to [`hail.vds`](https://hail.is/docs/0.2/vds/index.html):
- `hl.vds.lgt_to_get`
- Densify has become `hl.vds.to_dense_mt`

You're not the first person to report some surprise at the disappearance of `hail.experimental` items. I've made a note to clarify the description of the `hail.experimental` module. If you do need the docs for the old version of Hail you can find them [in the code](https://github.com/hail-is/hail/blob/0.2.119/hail/python/hail/experimental/vcf_combiner/densify.py) though I understand that's a more frustrating viewing experience.

Since you're referencing the old GVCF combiner, it sounds like you might be using what we call the old "merged sparse representation". In this representation, the reference and variant data is stored together in one Hail Matrix Table. We have found this representation error prone. Analysts often accidentally forget to properly handle the reference blocks. This representation is also slightly large than our new split representation: VDS.

You can convert back and forth between VDS and the "merged sparse representation":
1. VDS -> merged sparse representation: [`hl.vds.to_merged_sparse_representation(vds)`](https://hail.is/docs/0.2/vds/hail.vds.to_merged_sparse_mt.html#hail.vds.to_merged_sparse_mt) (but please note that the VDS does not necessarily store a reference allele for each reference block, so you might need to provide one [see details here](https://discuss.hail.is/t/vds-to-merged-sparse-matrix/3478/3))
2. [`hl.vds.VariantDataset.from_merged_representation(sparse_mt)`](https://hail.is/docs/0.2/vds/hail.vds.VariantDataset.html#hail.vds.VariantDataset.from_merged_representation)

We recommend that new projects use the VDS. It is a high-quality, durable solution which we've used to combine and analyze as many as 250k genomes and also 955k exomes.

Again, apologies for the disruption. The GVCF combiner became popular a little quicker than for which we were prepared.

**Comment by tdelcourt** [comment]
Hi, @danking ,

Thanks for the fast and detailed answer.
No worry, it didn't disrupt my workflow, but confused me since the pages are still in the search results but not available and I didn't see the note for moving to VDS in the changelogs.
