### ISSUE TITLE
[batch] Hail Batch workers can be starved of CPU and RAM by jobs

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13902]
### What happened?

The Batch worker currently gives the actual fraction of CPU time to the job containers. That means a 16-core job can monopolize all CPU time.

We also appear to lease out all the RAM to the jobs. The same issue, of course, can appear where the job takes all our resources away.

We should reserve some modest amount of CPU and RAM for the worker by not actually giving out the full CPU and RAM to the jobs. I'm not sure how much the worker needs, but presumably less than a full CPU and maybe a gigabyte of RAM?

### Version

0.2.124

**Comment by danking** [comment]
Could this have been affected by accounting changes from cgroups v2 which should have arrived in the new ubuntu base image.

**Comment by danking** [comment]
Let's try to reproduce with a CPU heavy workload using 16 cores.

Then let's try to reduce CPU and RAM requests to 95% of actual requested.

**Comment by jigold** [comment]
Ben confirmed his workloads use a lot of memory. My guess is we're not limiting the kernel memory and possibly the swap as well. The behavior we're seeing might be because the kernel is killing our worker container randomly and not the offending user jobs. Solution is to figure out how to limit the kernel memory and swap memory in crun to see if that makes a difference.
