### ISSUE TITLE
Mendel errors shouldn't report variants on the MT chromosome

### ISSUE THREAD

**Issue by ksatterstrom** [hail-is/hail#2005]
Because, you know, that one is maternally inherited.

**Comment by jbloom22** [comment]
The docs say: "This method assumes all contigs apart from X and Y are fully autosomal; mitochondria, decoys, etc. are not given special treatment."

I think this is the right behavior, since we cannot know all contig names in advance, and the user can filter variants before calling the method.

On the other hand, I think we should move this statement up and lengthen it to: "This method assumes all contigs apart from X and Y are fully autosomal; mitochondria, decoys, etc. are not given special treatment so should be filtered out prior to invocation."

**Comment by jbloom22** [comment]
I moved the line up. We will handle this more intelligently in 0.2 by incorporating info from the user-specified reference genome.
