### ISSUE TITLE
Call rate for sex chromosome

### ISSUE THREAD

**Issue by danfengc** [hail-is/hail#2078]
Hello,

I was using the following code to calculate the call rate for each variant, and comparing the result with RICOPILI output. I found some discrepancies between Hail output and RICOPILI output. Here is one example:

<img width="783" alt="screen shot 2017-08-08 at 4 25 46 pm" src="https://user-images.githubusercontent.com/20709374/29093013-467aeb1a-7c56-11e7-8b8d-03fe95aaa471.png">
And missing rate returned by RICOPILI for the same variant is 0.05112

I felt like that the missing rate has been overestimated by treating female and male equally, that is, females should be removed when trying to calculate variant that are located on non-PAR region of Y chromosome.

**Comment by jbloom22** [comment]
Hail treats all variants similarly when computing call rate since sex may not be known. If you have a sample annotation for sex, then to calculate call rate on nonParY you should filter variants to nonParY (https://hail.is/docs/stable/types.html#variant) and filter samples to males first (using the sample annotation) before calculating call rate.
