### ISSUE TITLE
Problems with VCF accumulator

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#371]
- says 'import clean' if you do importvcf with no execute commands
- multiplies all exclusions by the number of times the vcf was read (number of execute commands)

**Comment by cseed** [comment]
Hail tries to do a lot of data integrity checks and warn the user about problems.  We've found a number of bugs in upstream tools and workflows that were arguably incorrect.  But generating warnings when importing a 2TB file is a challenge in Spark.  Right now we use Spark's Accumulators to accumulate classes of error messages and write them out at the end of the pipeline run (see the VCFReport object).  However, we use them in non-actions and get incorrect reports (due to job restarts or reused stages in the pipeline).

I have an idea about how to fix this by accumulating only at the end of a successful mapPartitions operation and recording the stageId and taskAttemptId from the TaskContext.  The accumulator should only accumulate one of the reports from a successful mapPartitions.

Using this, I wanted to build an abstraction for reporting warnings and other messages reliably on large import steps.

If this works, we plan to float it up to the Spark mailing list to see if it can be of use, or at least write a nice blog post explaining how to get reliable accumulators in Spark.

See the discussion here for the current situation:

http://stackoverflow.com/questions/29494452/when-are-accumulators-truly-reliable

Closed as won't fix:

https://issues.apache.org/jira/browse/SPARK-732

Of course, I might be missing something obvious and this won't work.

**Comment by cseed** [comment]
report/accumulators have been removed: https://github.com/hail-is/hail/pull/2024.  No longer relevant.  .... although better input integrity checking and error reporting would still be nice.
