### ISSUE TITLE
filter_intervals cannot handle large interval lists

### ISSUE THREAD

**Issue by bavila-broad** [hail-is/hail#3942]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:

eb1e04205793

### What you did:

https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Class.20file.20too.20large!

Ran filter_intervals with 200k intervals, got Java "Class file too large!" error.

**Comment by danking** [comment]
@tpoterba The issue seems to be this line of `filter_intervals`:
```
    intervals = [wrap_input(x)._jrep for x in intervals.value]
```
I *think* `.value` is creating table for some reason that somehow contains the 200k intervals and is then calling collect on that table and then converting that to python (???) and then converting that to a java representation of an interval.

**Comment by tpoterba** [comment]
memory sharing is already on the roadmap, no need for this issue
