### ISSUE TITLE
support nested forAll in Gen

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#400]

**Comment by danking** [comment]
A few observations:

 - `Prop` is essentially a named `Gen[Unit]`

 - The type of `Prop.forAll` is `Gen[T] -> (U -> Boolean) -> Prop`

 - The first two observations suggest: `Prop.forAll` has type: `Gen[T] -> (U -> Boolean) -> Gen[Unit]`

 - A `Gen[Unit]` is a bit artificial because the test framework halts execution (presumably with an exception) when a counter-example is found. I instead prefer that `Prop.forAll` has type: `Gen[T] -> (U -> Boolean) -> Gen[Boolean]`

 - Now `Prop.forAll` has the same type as `Gen.flatMap[Boolean]`

It seems the difference between `forAll` and `flatMap` is that `forAll` conceptually preforms a product operation while `flatMap` performs a sampling. However, I think they are, in reality, the same operation: sampling.

The implementation for `GenProp3` looks like:

```scala
for (i <- 0 until p.count) {
  val v1 = g1(p)
  val v2 = g2(p)
  val v3 = g3(p)
  val r = f(v1, v2, v3)
  if (!r) {
    println(s"! ${prefix}Falsified after $i passed tests.")
    println(s"> ARG_0: $v1")
    println(s"> ARG_1: $v2")
    println(s"> ARG_2: $v3")
    assert(r)
  }
}
```

Which could be re-written as:

```scala
for (i <- 0 until p.count) {
  for (v1 <- g1
    v2 <- g2
    v3 <- g3) {
    if (!r) {
      println(s"! ${prefix}Falsified after $i passed tests.")
      println(s"> ARG_0: $v1")
      println(s"> ARG_1: $v2")
      println(s"> ARG_2: $v3")
      assert(r)
    }
  }
}
```

The primary difference between `flatMap` and `forAll` seems to be in error
reporting. So gen is currently a Reader monad on `Parameters`. If we add a
"forAll stack" to `Parameters` we could implement `forAll` as:

```scala
def forAll[T,U](gt: Gen[T], gu: T -> Gen[U]): Gen[U] =
  for (t <- gt; u <- local(pushQuantified(t), gu(t)) yield u

def pushQuantified(x: Any)(Parameters p): Paramters =
  new Parameters(p.rng, p.size, p.count, (x :: p.quanitifed))
```

We'd need to add the `local` operation to `Gen` complete the `Reader` monad:

```scala
// in class Gen
def local(modify: Parameters -> Parameters, gu: Gen[U]): Gen[U] =
  Gen { p => gu(modify(p)) }
```

Finally, the `check` method can access this stack of quantified variables to provide a useful error message.

Thoughts?

**Comment by danking** [comment]
Check is implemented something like:

```scala
for (i <- 0 until p.count) {
  (for (successP <- g;
    vars <- getTheForAllStack) {
    if (!successP) {
      printTheVariableStack(vars)
      assert(false)
    })(p)
}

```

**Comment by danking** [comment]
This isn't quite right. The `check` method will have no way to inspect the context of a sampled value (particularly, the sampled boolean from a proposition).

I think `Gen[T]` should probably be a `Reader[Parameters, (Seq[Any], T)]` where the `Seq[Any]` are the witnesses for each universally quantified variable.

**Comment by danking** [comment]
And we can get an implementation of `Reader` from a library calls `cats` which provides the `Kleisli` class. So we'd want to alias `Gen[T]` as `Kleisli[Id, Parameters, T]`.

**Comment by danking** [comment]
Options for nested `forAll`:

```scala
toProp(for (
  j <- forAll(Gen.choose(0, 10000));
  k <- forAll(Gen.choose(0, 10000));
) yield {
  val gt = if (j < k) GTPair(j, k) else GTPair(k, j)
  Genotype.gtPair(Genotype.gtIndex(gt)) == gt
}).check()
```

```scala
forAll(Gen.choose(0, 10000)) { (j: Int) =>
  forAll(Gen.choose(0, 10000)) { (k: Int) =>
    val gt = if (j < k) GTPair(j, k) else GTPair(k, j)
    Genotype.gtPair(Genotype.gtIndex(gt)) == gt
  }
}.check()
```

I think I can ditch the `toProp` on the do notation with an implicit conversion.
