### ISSUE TITLE
make Hail deterministic

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4017]
In particular, a sub-pipeline executed multiple times as part of a larger pipeline must be deterministic.

**Comment by catoverdrive** [comment]
The part of this that's not solved by #4104 is the preservation of relational values through optimization passes. For example, we expect the following to be true:
```
ht = hl.utils.range_table(10, 3)
ht1 = ht.annotate(x=hl.rand_unif(0, 1))
ht1.x.collect()[:5] == ht1.head(5).x.collect()
```

but since there exist two rules 
```
      case TableHead(TableMapRows(child, newRow, newKey, preservedKeyFields), n) =>
        TableMapRows(TableHead(child, n), newRow, newKey, preservedKeyFields)

      case TableHead(tr@TableRange(nRows, nPar), n) =>
        if (n < nRows) TableRange(n.toInt, (nPar.toFloat * n / nRows).toInt.max(1)) else tr
```
the underlying `TableRange` changes partitioning through the optimization pass and the results differ.
