### ISSUE TITLE
chi_squared_test returns wrong p-value

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4192]
```
hl.chi_squared_test(61, 17493, 95, 84145).value
```
returns:
```
Struct(p_value=1.0, odds_ratio=3.088661028321103)
```
whereas in R:
```
chisq.test(matrix(c(61, 17493, 95, 84145), nrow=2), correct = FALSE)
```
returns:
```
	Pearson's Chi-squared test

data:  matrix(c(61, 17493, 95, 84145), nrow = 2)
X-squared = 52.307, df = 1, p-value = 4.74710374058148e-13
```

**Comment by konradjk** [comment]
`fisher_exact_test` for the same set of numbers returns the same thing in R and hail

**Comment by konradjk** [comment]
Btw, props to Mark Daly for flagging the result that led me to find this one

**Comment by jbloom22** [comment]
This is an overflow bug that's existed since June 25: https://github.com/hail-is/hail/pull/3833

The implementation is vulnerable to `(a + b) * (c + d) * (b + d) * (a + c)` exceeding max int.
```
    val ad = a * d
    val bc = (b * c).toDouble
    val det = ad - bc
    val chiSquare = (det * det * (a + b + c + d)) / ((a + b) * (c + d) * (b + d) * (a + c))
```
The new implementation converts the ints to floats and is more robust if we switch to allowing float inputs.

**Comment by jbloom22** [comment]
http://discuss.hail.is/t/fixed-overflow-bug-in-0-2-chi-squared-test-contingency-table-test-present-since-june-25-2018/619
