### ISSUE TITLE
Kubernetes may fail to schedule in a reasonable time

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#5269]
###Hail version
N/A Kubernetes v1 API, cluster version 1.10.11

### What you did
Attempted to schedule a pod through app.hail.is. Waited ~20 minutes.

### What went wrong (all error messages here, including the full java stack trace)
Simply stuck in Not PodScheduled (status.condition contains an entry of {status: False, type: PodScheduled} )

This status is also verified using kubectl get pods -w

Total number of pods did not seem onerous by quantity alone, so this must be an issue of resource utilization by some of these pods.

```sh
NAME                                       READY     STATUS    RESTARTS   AGE
apiserver-8658d59d48-r8p6w                 1/1       Running   0          9d
auth-gateway-deployment-7d7cf8846f-l5m9b   1/1       Running   0          14h
batch-deployment-6448f84d9c-gxn2c          1/1       Running   0          1h
dk-test-58dffcd944-9xkkx                   1/1       Running   0          11d
frontend-766c875db4-cmpvx                  1/1       Running   0          8d
gateway-deployment-78c4dd64f5-tdnnc        1/1       Running   0          1h
hail-ci-deployment-5744fd6964-s29xb        1/1       Running   0          1h
image-fetcher-bkpcc                        1/1       Running   0          23m
image-fetcher-gb9rs                        1/1       Running   0          26m
image-fetcher-glj5p                        1/1       Running   0          25m
image-fetcher-kjd7z                        1/1       Running   0          23m
image-fetcher-vhv74                        1/1       Running   0          25m
image-fetcher-zppvc                        1/1       Running   0          24m
notebook-api-deployment-7bb85bfd-z6mvp     1/1       Running   0          12h
notebook-deployment-8546dbcb7c-zfc4r       1/1       Running   0          1h
notebook-worker-2lt2l                      1/1       Running   0          46m
notebook-worker-77nqq                      1/1       Running   0          1h
notebook-worker-fljx6                      1/1       Running   0          3h
notebook-worker-gm6lz                      1/1       Running   0          36m
notebook-worker-kj7bb                      1/1       Running   0          3h
notebook-worker-n8dgv                      0/1       Pending   0          4m
notebook-worker-pshdf                      1/1       Running   0          35m
scorecard-deployment-654f774444-vwpzr      1/1       Running   0          51m
site-deployment-6789bd6c5b-lxbxk           1/1       Running   0          51m
spark-master-6f7678b449-jcbnp              1/1       Running   0          9d
spark-worker-569866dff7-l452k              1/1       Running   0          9d
spark-worker-569866dff7-xzmx4              1/1       Running   0          9d
upload-658d7f8c7d-gvj4h                    1/1       Running   0          51m
web-deployment-bc6497cdb-qfc9g             1/1       Running   0          2h
```

**Comment by danking** [comment]
`kubectl describe pod POD_NAME` will tell you there reasons the pod could not be scheduled. I often see this issue when we run out of available CPU.

**Comment by akotlar** [comment]
Thanks. I assume that this was for some Kube-controlled resource. I opened this issue because I think we should make sure users don't see this. I was able to encounter it during yesterday's demo. It was chance that @cseed didn't. Had he, the demo would have not worked (took > 20 minutes for the next notebook to work). Conrad ran into this too.

A second question is what to do if we encounter this. Should we tell the user (CPU resources unavailable for instance)? I could see an argument for this: users should pay for resources they use, past some point. That kind of information would motivate them to purchase those resources. That kind of information can also give free-tier users some measure of understanding, acceptance (they don't pay, so it's ok to wait a bit). 

Encountering this situation and telling the nothing beyond the pod status (NotScheduled) should not be an option. Either users never encounter this, or we need to tell them something useful

**Comment by danking** [comment]
There is a kubernetes controlled resource that has been exhausted: CPU. CPU is provided by nodes (`kubectl get nodes`).

I agree, users should not see this.

The core issue is lack of sufficient CPU. We can resolve this in one of two ways:

1. add more non-preemptible nodes to the k8s cluster

2. make the non-preemptible node pool auto-scale

For tutorials, we increase the size of the non-preemptible node pool before the tutorial begins. We shrink it again (to save money) when the tutorial is over.

We could enable point two, but we now have two new issues:

1. AFAIK, the auto-scaler only adds nodes when resources are exhausted. Ergo, we only add more nodes when a pod becomes unscheduleable. When this happens, we must wait for a node to spin up (a couple minutes) to provide sufficient CPU for the pod. There has been work towards teaching the auto-scaler about "slack" or "buffer" resources, but [the relevant PR was abandoned in Dec 2017](https://github.com/kubernetes/autoscaler/pull/77).

2. Once the node is alive, it needs to download the docker image so it can schedule the pod. We use a `DaemonSet` to ensure that the latest notebook images is always cached on all nodes. Hail's notebook images are very large. They take about two minutes to download

Actions we can take:

1. Investigate a system for ensuring our cluster always sufficient CPU for another N notebooks. (i.e. have CPU slack)
2. Shrink our notebook images. We need to get off `conda` (for all our projects). Their `jupyter/scipy-notebook` image is 4.16GB.

I think this is more of a long-term issue because point 1 is rather tricky and we have only a handful of users right now (so we can set a static cluster size that is sufficiently large).

**Comment by akotlar** [comment]
Sounds good Dan, and agreed it's a long term issue. Regarding point 2, I also don't really like the idea of non-preemtible nodes from a resource utilization standpoint.

I think we could probably write our own peak load predictor, or use one of the existing tools, outside of the kube ecosystem.  There has been some interesting work using some relatively simple learning models to predict load. https://medium.com/netflix-techblog/scryer-netflixs-predictive-auto-scaling-engine-a3f8fc922270
