### ISSUE TITLE
error for using "importannotations table"

### ISSUE THREAD

**Issue by fenglongsun** [hail-is/hail#561]
I am a fresh user for hail.
I try this command "hail importannotations table variantAnnotations.alternateformat.tsv  -e Variant --impute write   -o consequences.vds", but I received an error message as follow "hail: fatal: importannotations table: parse error: "-e" is not a valid option", why?
additionally, I can not find the corresponding test file in the test file of hail download from here and it is really very inconvenient for me to test it!
thanks a lot!

**Comment by tpoterba** [comment]
Hi!
This is an odd error message to get -- is your repository updated to the current master?  There was an update to the `importannotations table` module a few weeks ago, before which the `-e` option didn't exist.  

We are in the midst of a documentation reorganization, so I apologize if it's difficult to find things at the moment.  From the cloned repository, all test files are at `src/test/resources/*`.  

This command worked for me just now:
```
hail importannotations table src/test/resources/variantAnnotations.alternateformat.tsv --impute -e '`Chromosome:Position:Ref:Alt`' write -o tmp.vds
```

The `-e` argument uses an expression to specify how to construct a `Variant`, which in this case is just the column name since the type of that column is `Variant`.  If we don't use the `--impute` argument, we can construct it with 
```
-e 'Variant(`Chromosome:Position:Ref:Alt`)'
```
More info on that [here](https://github.com/broadinstitute/hail/blob/master/docs/commands/ImportAnnotations.md)

**Comment by cseed** [comment]
@fenglongsun Are you still having trouble with importannotations?  Note we reorganized the documentation and the documentation for importanntations table is [here](https://hail.is/docs/devel/index.html#importannotations_table).

**Comment by jbloom22** [comment]
@fenglongsun I am closing this since we haven't heard back from you, but let us know if you need more help.
