### ISSUE TITLE
add Set constructor

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#598]

**Comment by cseed** [comment]
Should support empty Set construction.

**Comment by lfrancioli** [comment]
Reviving this as would be great to have! I haven't added it myself since we discussed using the python way using `{}` (e.g. `{ 1 , 2 ,3}`). When I looked at implementing it based on the Array constructor, I saw some of the compiler things @danking added, so wasn't sure how safe it was to just mimic it.

**Comment by tpoterba** [comment]
I think we should use all the python constructor syntaxes.
`[ 1, 2 ]` = list
`{ 1, 2 }` = set
`{ 1:"foo", 2:"bar" }` = dict

struct constructor TBD

**Comment by lfrancioli** [comment]
I like it!

**Comment by danking** [comment]
I still have my money on
```
[ foo : "foo", bar : "bar" ]
```
for structs

**Comment by tpoterba** [comment]
I like that

**Comment by lfrancioli** [comment]
Me too!

This will be great :)

**Comment by cseed** [comment]
I was rooting for the much under-appreciated angle brackets: `<foo: "foo", bar: "bar>`.

**Comment by danking** [comment]
The fact that those are also used for infix operators is evoking YACC horrors for me.

**Comment by tpoterba** [comment]
Exists in hail2.
