### ISSUE TITLE
fix 404s in documentation

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#606]
File naming/capitalization issue?

**Comment by jigold** [comment]
@cseed: Is this issue for the files that are known to exist but get 404 errors (due to capitalization with the importbgen etc. files) or all 404 errors? I don't think we can remove the 404 errors from the console for any command that doesn't have a corresponding markdown file in the commands directory. See this link: http://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up

**Comment by johnc1231** [comment]
Considering how old this is and the migration to sphinx, is this still relevant? I assume not, so we should probably close it.
