### ISSUE TITLE
add `conda install jupyter` to installation setup?

### ISSUE THREAD

**Issue by raynamharris** [hail-is/hail#7136]
I'm running hail version 0.2.23 and python 3.7.4 in a conda environment as described in the [installation instructions for mac os](https://hail.is/docs/0.2/getting_started.html#installing-hail-on-mac-os-x-or-gnu-linux-with-pip).  The tutorials worked fine when I ran them from the command line using ipython, but when I launched a jupyter notebook, I kept getting a `ModuleNotFoundError` when running `import hail as hl`. I solved the problem by first running `conda install jupyter` in my virtual environment. Am i the only one who had this issue? If not, please consider adding this extra step to the installation instructions.

**Comment by tpoterba** [comment]
Sorry you hit this -- I think I understand what happened.

Since we don't include jupyter as a Hail package dependency (it's a large dependency and pulls in a host of transitive dependencies as well), when you ran `jupyter` you picked up a different `jupyter` (probably the conda base environment one, which uses an entirely different Python installation). 

I don't want to add jupyter as a dependency, but we can certainly add a note in the tutorials landing page.
