### ISSUE TITLE
documentation didn't update

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#733]
The latest doc changes (edit link) didn't get pushed to the live docs.

**Comment by danking** [comment]
Looking at it.

**Comment by danking** [comment]
I don't think I actually understand how artifact and snapshot dependencies work in TeamCity. I thought a build by the main build configuration (the regular CI) would trigger a build of the docs build configuration. This was not the case and I'm not sure why.

I've set up the docs build to trigger on any change to master. Unfortunately, we have to `compileScala` twice because these are separate builds.

I'll add an issue to clean this up and make it more sensible. There's got to be a right way to do this.

**Comment by danking** [comment]
The docs now trigger appropriately on changes to master, but I haven't made them trigger from successful code builds yet.
