### ISSUE TITLE
Duplicate variant bug

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#869]
Maryam encountered this bug in one chunk of a 7 TB VCF.  The end of one partition and beginning of the next were the same variant.  Spark shell readout:

``` scala
scala> val zipped = sc.textFile("<vcf.bgz>")
zipped: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[1] at textFile at <console>:21

scala> zipped.count()
res2: Long = 71308

scala> val unzipped = sc.textFile("<unzipped vcf>")
unzipped: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[3] at textFile at <console>:21

scala> unzipped.count()
res3: Long = 71307

 scala> val zipped2 = sc.textFile("<vcf.bgz>", 1000)
zipped2: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[7] at textFile at <console>:21

scala> zipped2.count()
res10: Long = 71307
```

I am inclined to think this is an issue in the BGZip codec.

**Comment by tomwhite** [comment]
I wonder if this occurs with the Hadoop-BAM codec too? I think the issue before that led to it being reverted (https://github.com/hail-is/hail/issues/566) was because the split size was too small, which would be fairly easy to fix by putting a limit in place (so that -b/-n are hints, in other words). I'd be happy to work on such a change.

From a maintainability point of view it would be best if we could have a single codec that is shared (GATK is using the Hadoop-BAM codec, for example) so we don't duplicate work.

**Comment by tpoterba** [comment]
Cotton fixed the problem in our BGZip codec, but we'd love to use the Hadoop-BAM codec if that one works.

**Comment by tpoterba** [comment]
stale, closing.
